kind: pipeline
type: docker
name: production
steps:
  - name: lint
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
      - golangci-lint run --config golangci.yml
    failure: ignore